export interface Country {
  code: string;
  flag: string;
  name: string;
  nationality: string;
}

export const COUNTRIES: Country[] = [
  { code: "AF", flag: "🇦🇫", name: "Afghanistan", nationality: "Afghan" },
  { code: "AL", flag: "🇦🇱", name: "Albania", nationality: "Albanian" },
  { code: "DZ", flag: "🇩🇿", name: "Algeria", nationality: "Algerian" },
  { code: "AD", flag: "🇦🇩", name: "Andorra", nationality: "Andorran" },
  { code: "AO", flag: "🇦🇴", name: "Angola", nationality: "Angolan" },
  { code: "AG", flag: "🇦🇬", name: "Antigua and Barbuda", nationality: "Antiguan" },
  { code: "AR", flag: "🇦🇷", name: "Argentina", nationality: "Argentine" },
  { code: "AM", flag: "🇦🇲", name: "Armenia", nationality: "Armenian" },
  { code: "AU", flag: "🇦🇺", name: "Australia", nationality: "Australian" },
  { code: "AT", flag: "🇦🇹", name: "Austria", nationality: "Austrian" },
  { code: "AZ", flag: "🇦🇿", name: "Azerbaijan", nationality: "Azerbaijani" },
  { code: "BS", flag: "🇧🇸", name: "Bahamas", nationality: "Bahamian" },
  { code: "BH", flag: "🇧🇭", name: "Bahrain", nationality: "Bahraini" },
  { code: "BD", flag: "🇧🇩", name: "Bangladesh", nationality: "Bangladeshi" },
  { code: "BB", flag: "🇧🇧", name: "Barbados", nationality: "Barbadian" },
  { code: "BY", flag: "🇧🇾", name: "Belarus", nationality: "Belarusian" },
  { code: "BE", flag: "🇧🇪", name: "Belgium", nationality: "Belgian" },
  { code: "BZ", flag: "🇧🇿", name: "Belize", nationality: "Belizean" },
  { code: "BJ", flag: "🇧🇯", name: "Benin", nationality: "Beninese" },
  { code: "BT", flag: "🇧🇹", name: "Bhutan", nationality: "Bhutanese" },
  { code: "BO", flag: "🇧🇴", name: "Bolivia", nationality: "Bolivian" },
  { code: "BA", flag: "🇧🇦", name: "Bosnia and Herzegovina", nationality: "Bosnian" },
  { code: "BW", flag: "🇧🇼", name: "Botswana", nationality: "Motswana" },
  { code: "BN", flag: "🇧🇳", name: "Brunei", nationality: "Bruneian" },
  { code: "BG", flag: "🇧🇬", name: "Bulgaria", nationality: "Bulgarian" },
  { code: "BF", flag: "🇧🇫", name: "Burkina Faso", nationality: "Burkinabé" },
  { code: "BI", flag: "🇧🇮", name: "Burundi", nationality: "Burundian" },
  { code: "KH", flag: "🇰🇭", name: "Cambodia", nationality: "Cambodian" },
  { code: "CM", flag: "🇨🇲", name: "Cameroon", nationality: "Cameroonian" },
  { code: "CA", flag: "🇨🇦", name: "Canada", nationality: "Canadian" },
  { code: "CV", flag: "🇨🇻", name: "Cape Verde", nationality: "Cape Verdean" },
  { code: "CF", flag: "🇨🇫", name: "Central African Republic", nationality: "Central African" },
  { code: "TD", flag: "🇹🇩", name: "Chad", nationality: "Chadian" },
  { code: "CL", flag: "🇨🇱", name: "Chile", nationality: "Chilean" },
  { code: "CN", flag: "🇨🇳", name: "China", nationality: "Chinese" },
  { code: "CO", flag: "🇨🇴", name: "Colombia", nationality: "Colombian" },
  { code: "KM", flag: "🇰🇲", name: "Comoros", nationality: "Comorian" },
  { code: "CG", flag: "🇨🇬", name: "Congo", nationality: "Congolese" },
  { code: "CR", flag: "🇨🇷", name: "Costa Rica", nationality: "Costa Rican" },
  { code: "HR", flag: "🇭🇷", name: "Croatia", nationality: "Croatian" },
  { code: "CU", flag: "🇨🇺", name: "Cuba", nationality: "Cuban" },
  { code: "CY", flag: "🇨🇾", name: "Cyprus", nationality: "Cypriot" },
  { code: "CZ", flag: "🇨🇿", name: "Czech Republic", nationality: "Czech" },
  { code: "DK", flag: "🇩🇰", name: "Denmark", nationality: "Danish" },
  { code: "DJ", flag: "🇩🇯", name: "Djibouti", nationality: "Djiboutian" },
  { code: "DM", flag: "🇩🇲", name: "Dominica", nationality: "Dominican" },
  { code: "DO", flag: "🇩🇴", name: "Dominican Republic", nationality: "Dominican" },
  { code: "EC", flag: "🇪🇨", name: "Ecuador", nationality: "Ecuadorian" },
  { code: "EG", flag: "🇪🇬", name: "Egypt", nationality: "Egyptian" },
  { code: "SV", flag: "🇸🇻", name: "El Salvador", nationality: "Salvadoran" },
  { code: "GQ", flag: "🇬🇶", name: "Equatorial Guinea", nationality: "Equatoguinean" },
  { code: "ER", flag: "🇪🇷", name: "Eritrea", nationality: "Eritrean" },
  { code: "EE", flag: "🇪🇪", name: "Estonia", nationality: "Estonian" },
  { code: "SZ", flag: "🇸🇿", name: "Eswatini", nationality: "Swazi" },
  { code: "ET", flag: "🇪🇹", name: "Ethiopia", nationality: "Ethiopian" },
  { code: "FJ", flag: "🇫🇯", name: "Fiji", nationality: "Fijian" },
  { code: "FI", flag: "🇫🇮", name: "Finland", nationality: "Finnish" },
  { code: "FR", flag: "🇫🇷", name: "France", nationality: "French" },
  { code: "GA", flag: "🇬🇦", name: "Gabon", nationality: "Gabonese" },
  { code: "GM", flag: "🇬🇲", name: "Gambia", nationality: "Gambian" },
  { code: "GE", flag: "🇬🇪", name: "Georgia", nationality: "Georgian" },
  { code: "DE", flag: "🇩🇪", name: "Germany", nationality: "German" },
  { code: "GH", flag: "🇬🇭", name: "Ghana", nationality: "Ghanaian" },
  { code: "GR", flag: "🇬🇷", name: "Greece", nationality: "Greek" },
  { code: "GD", flag: "🇬🇩", name: "Grenada", nationality: "Grenadian" },
  { code: "GT", flag: "🇬🇹", name: "Guatemala", nationality: "Guatemalan" },
  { code: "GN", flag: "🇬🇳", name: "Guinea", nationality: "Guinean" },
  { code: "GW", flag: "🇬🇼", name: "Guinea-Bissau", nationality: "Bissau-Guinean" },
  { code: "GY", flag: "🇬🇾", name: "Guyana", nationality: "Guyanese" },
  { code: "HT", flag: "🇭🇹", name: "Haiti", nationality: "Haitian" },
  { code: "HN", flag: "🇭🇳", name: "Honduras", nationality: "Honduran" },
  { code: "HU", flag: "🇭🇺", name: "Hungary", nationality: "Hungarian" },
  { code: "IS", flag: "🇮🇸", name: "Iceland", nationality: "Icelandic" },
  { code: "IN", flag: "🇮🇳", name: "India", nationality: "Indian" },
  { code: "ID", flag: "🇮🇩", name: "Indonesia", nationality: "Indonesian" },
  { code: "IR", flag: "🇮🇷", name: "Iran", nationality: "Iranian" },
  { code: "IQ", flag: "🇮🇶", name: "Iraq", nationality: "Iraqi" },
  { code: "IE", flag: "🇮🇪", name: "Ireland", nationality: "Irish" },
  { code: "IL", flag: "🇮🇱", name: "Israel", nationality: "Israeli" },
  { code: "IT", flag: "🇮🇹", name: "Italy", nationality: "Italian" },
  { code: "CI", flag: "🇨🇮", name: "Ivory Coast", nationality: "Ivorian" },
  { code: "JM", flag: "🇯🇲", name: "Jamaica", nationality: "Jamaican" },
  { code: "JP", flag: "🇯🇵", name: "Japan", nationality: "Japanese" },
  { code: "JO", flag: "🇯🇴", name: "Jordan", nationality: "Jordanian" },
  { code: "KZ", flag: "🇰🇿", name: "Kazakhstan", nationality: "Kazakhstani" },
  { code: "KE", flag: "🇰🇪", name: "Kenya", nationality: "Kenyan" },
  { code: "KI", flag: "🇰🇮", name: "Kiribati", nationality: "I-Kiribati" },
  { code: "KW", flag: "🇰🇼", name: "Kuwait", nationality: "Kuwaiti" },
  { code: "KG", flag: "🇰🇬", name: "Kyrgyzstan", nationality: "Kyrgyz" },
  { code: "LA", flag: "🇱🇦", name: "Laos", nationality: "Lao" },
  { code: "LV", flag: "🇱🇻", name: "Latvia", nationality: "Latvian" },
  { code: "LB", flag: "🇱🇧", name: "Lebanon", nationality: "Lebanese" },
  { code: "LS", flag: "🇱🇸", name: "Lesotho", nationality: "Mosotho" },
  { code: "LR", flag: "🇱🇷", name: "Liberia", nationality: "Liberian" },
  { code: "LY", flag: "🇱🇾", name: "Libya", nationality: "Libyan" },
  { code: "LI", flag: "🇱🇮", name: "Liechtenstein", nationality: "Liechtensteiner" },
  { code: "LT", flag: "🇱🇹", name: "Lithuania", nationality: "Lithuanian" },
  { code: "LU", flag: "🇱🇺", name: "Luxembourg", nationality: "Luxembourgish" },
  { code: "MG", flag: "🇲🇬", name: "Madagascar", nationality: "Malagasy" },
  { code: "MW", flag: "🇲🇼", name: "Malawi", nationality: "Malawian" },
  { code: "MY", flag: "🇲🇾", name: "Malaysia", nationality: "Malaysian" },
  { code: "MV", flag: "🇲🇻", name: "Maldives", nationality: "Maldivian" },
  { code: "ML", flag: "🇲🇱", name: "Mali", nationality: "Malian" },
  { code: "MT", flag: "🇲🇹", name: "Malta", nationality: "Maltese" },
  { code: "MR", flag: "🇲🇷", name: "Mauritania", nationality: "Mauritanian" },
  { code: "MU", flag: "🇲🇺", name: "Mauritius", nationality: "Mauritian" },
  { code: "MX", flag: "🇲🇽", name: "Mexico", nationality: "Mexican" },
  { code: "MD", flag: "🇲🇩", name: "Moldova", nationality: "Moldovan" },
  { code: "MC", flag: "🇲🇨", name: "Monaco", nationality: "Monégasque" },
  { code: "MN", flag: "🇲🇳", name: "Mongolia", nationality: "Mongolian" },
  { code: "ME", flag: "🇲🇪", name: "Montenegro", nationality: "Montenegrin" },
  { code: "MA", flag: "🇲🇦", name: "Morocco", nationality: "Moroccan" },
  { code: "MZ", flag: "🇲🇿", name: "Mozambique", nationality: "Mozambican" },
  { code: "MM", flag: "🇲🇲", name: "Myanmar", nationality: "Burmese" },
  { code: "NA", flag: "🇳🇦", name: "Namibia", nationality: "Namibian" },
  { code: "NR", flag: "🇳🇷", name: "Nauru", nationality: "Nauruan" },
  { code: "NP", flag: "🇳🇵", name: "Nepal", nationality: "Nepali" },
  { code: "NL", flag: "🇳🇱", name: "Netherlands", nationality: "Dutch" },
  { code: "NZ", flag: "🇳🇿", name: "New Zealand", nationality: "New Zealander" },
  { code: "NI", flag: "🇳🇮", name: "Nicaragua", nationality: "Nicaraguan" },
  { code: "NE", flag: "🇳🇪", name: "Niger", nationality: "Nigerien" },
  { code: "NG", flag: "🇳🇬", name: "Nigeria", nationality: "Nigerian" },
  { code: "KP", flag: "🇰🇵", name: "North Korea", nationality: "North Korean" },
  { code: "MK", flag: "🇲🇰", name: "North Macedonia", nationality: "Macedonian" },
  { code: "NO", flag: "🇳🇴", name: "Norway", nationality: "Norwegian" },
  { code: "OM", flag: "🇴🇲", name: "Oman", nationality: "Omani" },
  { code: "PK", flag: "🇵🇰", name: "Pakistan", nationality: "Pakistani" },
  { code: "PA", flag: "🇵🇦", name: "Panama", nationality: "Panamanian" },
  { code: "PG", flag: "🇵🇬", name: "Papua New Guinea", nationality: "Papua New Guinean" },
  { code: "PY", flag: "🇵🇾", name: "Paraguay", nationality: "Paraguayan" },
  { code: "PE", flag: "🇵🇪", name: "Peru", nationality: "Peruvian" },
  { code: "PH", flag: "🇵🇭", name: "Philippines", nationality: "Filipino" },
  { code: "PL", flag: "🇵🇱", name: "Poland", nationality: "Polish" },
  { code: "PT", flag: "🇵🇹", name: "Portugal", nationality: "Portuguese" },
  { code: "QA", flag: "🇶🇦", name: "Qatar", nationality: "Qatari" },
  { code: "RO", flag: "🇷🇴", name: "Romania", nationality: "Romanian" },
  { code: "RU", flag: "🇷🇺", name: "Russia", nationality: "Russian" },
  { code: "RW", flag: "🇷🇼", name: "Rwanda", nationality: "Rwandan" },
  { code: "KN", flag: "🇰🇳", name: "Saint Kitts and Nevis", nationality: "Kittitian" },
  { code: "LC", flag: "🇱🇨", name: "Saint Lucia", nationality: "Saint Lucian" },
  { code: "VC", flag: "🇻🇨", name: "Saint Vincent and the Grenadines", nationality: "Vincentian" },
  { code: "WS", flag: "🇼🇸", name: "Samoa", nationality: "Samoan" },
  { code: "SM", flag: "🇸🇲", name: "San Marino", nationality: "Sammarinese" },
  { code: "ST", flag: "🇸🇹", name: "São Tomé and Príncipe", nationality: "São Toméan" },
  { code: "SA", flag: "🇸🇦", name: "Saudi Arabia", nationality: "Saudi" },
  { code: "SN", flag: "🇸🇳", name: "Senegal", nationality: "Senegalese" },
  { code: "RS", flag: "🇷🇸", name: "Serbia", nationality: "Serbian" },
  { code: "SC", flag: "🇸🇨", name: "Seychelles", nationality: "Seychellois" },
  { code: "SL", flag: "🇸🇱", name: "Sierra Leone", nationality: "Sierra Leonean" },
  { code: "SG", flag: "🇸🇬", name: "Singapore", nationality: "Singaporean" },
  { code: "SK", flag: "🇸🇰", name: "Slovakia", nationality: "Slovak" },
  { code: "SI", flag: "🇸🇮", name: "Slovenia", nationality: "Slovenian" },
  { code: "SB", flag: "🇸🇧", name: "Solomon Islands", nationality: "Solomon Islander" },
  { code: "SO", flag: "🇸🇴", name: "Somalia", nationality: "Somali" },
  { code: "ZA", flag: "🇿🇦", name: "South Africa", nationality: "South African" },
  { code: "KR", flag: "🇰🇷", name: "South Korea", nationality: "South Korean" },
  { code: "SS", flag: "🇸🇸", name: "South Sudan", nationality: "South Sudanese" },
  { code: "ES", flag: "🇪🇸", name: "Spain", nationality: "Spanish" },
  { code: "LK", flag: "🇱🇰", name: "Sri Lanka", nationality: "Sri Lankan" },
  { code: "SD", flag: "🇸🇩", name: "Sudan", nationality: "Sudanese" },
  { code: "SR", flag: "🇸🇷", name: "Suriname", nationality: "Surinamese" },
  { code: "SE", flag: "🇸🇪", name: "Sweden", nationality: "Swedish" },
  { code: "CH", flag: "🇨🇭", name: "Switzerland", nationality: "Swiss" },
  { code: "SY", flag: "🇸🇾", name: "Syria", nationality: "Syrian" },
  { code: "TW", flag: "🇹🇼", name: "Taiwan", nationality: "Taiwanese" },
  { code: "TJ", flag: "🇹🇯", name: "Tajikistan", nationality: "Tajik" },
  { code: "TZ", flag: "🇹🇿", name: "Tanzania", nationality: "Tanzanian" },
  { code: "TH", flag: "🇹🇭", name: "Thailand", nationality: "Thai" },
  { code: "TL", flag: "🇹🇱", name: "Timor-Leste", nationality: "Timorese" },
  { code: "TG", flag: "🇹🇬", name: "Togo", nationality: "Togolese" },
  { code: "TO", flag: "🇹🇴", name: "Tonga", nationality: "Tongan" },
  { code: "TT", flag: "🇹🇹", name: "Trinidad and Tobago", nationality: "Trinidadian" },
  { code: "TN", flag: "🇹🇳", name: "Tunisia", nationality: "Tunisian" },
  { code: "TR", flag: "🇹🇷", name: "Turkey", nationality: "Turkish" },
  { code: "TM", flag: "🇹🇲", name: "Turkmenistan", nationality: "Turkmen" },
  { code: "TV", flag: "🇹🇻", name: "Tuvalu", nationality: "Tuvaluan" },
  { code: "UG", flag: "🇺🇬", name: "Uganda", nationality: "Ugandan" },
  { code: "UA", flag: "🇺🇦", name: "Ukraine", nationality: "Ukrainian" },
  { code: "AE", flag: "🇦🇪", name: "United Arab Emirates", nationality: "Emirati" },
  { code: "GB", flag: "🇬🇧", name: "United Kingdom", nationality: "British" },
  { code: "US", flag: "🇺🇸", name: "United States", nationality: "American" },
  { code: "UY", flag: "🇺🇾", name: "Uruguay", nationality: "Uruguayan" },
  { code: "UZ", flag: "🇺🇿", name: "Uzbekistan", nationality: "Uzbek" },
  { code: "VU", flag: "🇻🇺", name: "Vanuatu", nationality: "Ni-Vanuatu" },
  { code: "VA", flag: "🇻🇦", name: "Vatican City", nationality: "Vatican" },
  { code: "VE", flag: "🇻🇪", name: "Venezuela", nationality: "Venezuelan" },
  { code: "VN", flag: "🇻🇳", name: "Vietnam", nationality: "Vietnamese" },
  { code: "YE", flag: "🇾🇪", name: "Yemen", nationality: "Yemeni" },
  { code: "ZM", flag: "🇿🇲", name: "Zambia", nationality: "Zambian" },
  { code: "ZW", flag: "🇿🇼", name: "Zimbabwe", nationality: "Zimbabwean" },
];
